CREATE TABLE beer_style (
	BEER_NAME VARCHAR(100),
	BEER_STYLE VARCHAR(100),
	CATEGORY VARCHAR(50),
	BREWERY VARCHAR(100),
	ADDRESS VARCHAR(100),
	STATE VARCHAR(50),
	COUNTRY VARCHAR(50),
	COORDINATES VARCHAR(50)
);

SELECT * FROM beer_style